package sg.dhs.checker

import android.content.Intent
import android.os.Bundle
import android.support.design.widget.Snackbar
import android.support.v7.app.AppCompatActivity
import android.widget.EditText

import kotlinx.android.synthetic.main.activity_main_menu.*
import kotlinx.android.synthetic.main.content_main_menu.*

/**
 * The activity that's launched if you start the app from the home screen.
 * It's literally just a text box to type queries
 */
class MainMenu : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        // Initialise the activity with the view, and other things
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main_menu)
        setSupportActionBar(toolbar)

        // Add a click listener to the floating action bar on the bottom right
        // the variable `fab` is magically generated by kotlinx, don't worry about it
        fab.setOnClickListener { view ->
            // start a "share" intent (ACTION_SEND)
            val queryIntent = Intent(Intent.ACTION_SEND)
            // put the text from the text box into the share intent
            // queryButton is actually the text box, not the button
            queryIntent.putExtra(Intent.EXTRA_TEXT, (queryButton as EditText).text.toString())
            // make sure to tell android that it's a text intent
            queryIntent.setType("text/plain")
            // and fire the activity
            startActivity(queryIntent)
        }
    }

}
